### ISSUE TITLE
Wrong Github URLs in installation chapter

### ISSUE THREAD

**Issue by theGreatWhiteShark** [polymode/polymode.github.io#1]
Hey Vitalie,

Nice Github Pages documentation!

In the **Manually** section of the **Installation** chapter you got the wrong Github URLs to your packages.

> cd path/to/vc/dir
> git clone https://github.com/emacs-polymode/polymode
> git clone https://github.com/emacs-polymode/poly-markdown

For now it should be **github.com/polymode/..** instead of _/emacs-polymode/_.

Also I would suggest to put the installation chapter in the README.md as well. It's always nice to have some idea how to start right away.

**Comment by vspinu** [comment]
Thanks. I don't want to duplicate things, but I could add a direct link to the installation section.

**Comment by theGreatWhiteShark** [comment]
Sounds good too
